#!/usr/bin/bash

# settings
local_path=$( dirname $( readlink -f $0 ) )
src="$local_path/public"
host='web1.mx-os.mx'
remote_path='/srv/www/html/mx-os.mx/default/public'

# go there
cd "$local_path"

# sync
rsync -Plrtz --delete $src/ $host:$remote_path/
